#!/bin/bash
INSTALL=/opt/agorum/agorumcore
SERVER=$INSTALL/jboss/server/default
JOBS=$(ps -fa | grep agorumcore | wc -l)
[ $JOBS -gt 1 ] && RUNNING=true

case "$1" in
    stop)   [ "$RUNNING" ] && $INSTALL/scripts/agorumcore stop
            ;;
    start)  [ "$RUNNING" ] || $INSTALL/scripts/agorumcore start
            ;;
    log)    [ "$RUNNING" ] && exec tail -f $SERVER/log/server.log
            ;;
    status) [ "$RUNNING" ] && { ret=0; status=running; } || { ret=1; status=stopped; }
            echo "$status"
            exit $ret
            ;;
    root|server|default) ( cd $SERVER && exec bash )
            ;;
esac
