#!/bin/bash
INSTALL=/opt/agorum/agorumcore
SERVER=$INSTALL/jboss/server/default
JOBS=$(ps -efa | grep agorumcore | wc -l)
[ $JOBS -gt 1 ] && RUNNING=true

case "$1" in
    stop)   [ "$RUNNING" ] && $INSTALL/scripts/agorumcore stop
            ;;
    start)  [ "$RUNNING" ] || $INSTALL/scripts/agorumcore start
            ;;
    log)    [ "$RUNNING" ] && exec tail -f $SERVER/log/server.log
            ;;
    status) [ "$RUNNING" ] && { ret=0; status=running; } || { ret=1; status=stopped; }
            echo "$status"
            exit $ret
            ;;

     #
     # change directory usage: . agorum <default>
     # without subshell creation
     # 

    root|server|default)
            cd $SERVER 
            ;;
    messages)
            cd /opt/agorum/agorumcore/jboss/server/default/deploy/roi.ear/roiwebui.war/WEB-INF/config/messages
            ;;
esac
