#!/usr/bin/env bash

set -x

sigusr1_handler() {
    echo "sigusr1_handler" 
    ps -efa
}

sigterm_handler() {
    echo "sigterm_handler" 
    ps -ef
    exit 143; # 128 + 15 -- SIGTERM
}

# setup handlers
# on callback, kill the last background process, which is `tail -f /dev/null` and execute the specified handler
trap 'sigusr1_handler' SIGUSR1
trap 'sigterm_handler' SIGTERM

# run application
/opt/agorum/agorumcore/scripts/agorumcore start
#pid="$!"
#echo $pid

ps -efa

# wait forever
while true
do
  tail -f /dev/null & wait ${!}
done
